//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace DiscountMe.DiscountMeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.iberasoft.com/webservices", ConfigurationName="DiscountMeService.DiscountMeServiceSoap")]
    public interface DiscountMeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.iberasoft.com/webservices/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadBase))]
        System.IAsyncResult BeginLogin(string username, string password, string uniqueId, System.AsyncCallback callback, object asyncState);
        
        DiscountMe.DiscountMeService.User EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.iberasoft.com/webservices/ListaCategorias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadBase))]
        System.IAsyncResult BeginListaCategorias(System.AsyncCallback callback, object asyncState);
        
        DiscountMe.DiscountMeService.DiscountCategory[] EndListaCategorias(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.iberasoft.com/webservices/DescuentosCercanos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntidadBase))]
        System.IAsyncResult BeginDescuentosCercanos(double latitud, double longitud, string texto, int rango, DiscountMe.DiscountMeService.DiscountCategory category, string medida, System.AsyncCallback callback, object asyncState);
        
        DiscountMe.DiscountMeService.DiscountDTO[] EndDescuentosCercanos(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class User : EntidadBase {
        
        private string nameField;
        
        private string surnameField;
        
        private string userNameField;
        
        private string passwordField;
        
        private string emailField;
        
        private string passwordSaltField;
        
        private System.DateTime createDateField;
        
        private System.DateTime lastModifiedDateField;
        
        private System.DateTime lastLoginDateField;
        
        private string lastLoginIpField;
        
        private bool isActivatedField;
        
        private bool isLockedOutField;
        
        private System.DateTime lastLockedOutDateField;
        
        private string newPasswordKeyField;
        
        private System.DateTime newPasswordRequestedDateField;
        
        private string newEmailKeyField;
        
        private Rol[] rolesField;
        
        private UserPreferences[] preferencesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PasswordSalt {
            get {
                return this.passwordSaltField;
            }
            set {
                this.passwordSaltField = value;
                this.RaisePropertyChanged("PasswordSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime LastLoginDate {
            get {
                return this.lastLoginDateField;
            }
            set {
                this.lastLoginDateField = value;
                this.RaisePropertyChanged("LastLoginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LastLoginIp {
            get {
                return this.lastLoginIpField;
            }
            set {
                this.lastLoginIpField = value;
                this.RaisePropertyChanged("LastLoginIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
                this.RaisePropertyChanged("IsActivated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsLockedOut {
            get {
                return this.isLockedOutField;
            }
            set {
                this.isLockedOutField = value;
                this.RaisePropertyChanged("IsLockedOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime LastLockedOutDate {
            get {
                return this.lastLockedOutDateField;
            }
            set {
                this.lastLockedOutDateField = value;
                this.RaisePropertyChanged("LastLockedOutDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NewPasswordKey {
            get {
                return this.newPasswordKeyField;
            }
            set {
                this.newPasswordKeyField = value;
                this.RaisePropertyChanged("NewPasswordKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public System.DateTime NewPasswordRequestedDate {
            get {
                return this.newPasswordRequestedDateField;
            }
            set {
                this.newPasswordRequestedDateField = value;
                this.RaisePropertyChanged("NewPasswordRequestedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NewEmailKey {
            get {
                return this.newEmailKeyField;
            }
            set {
                this.newEmailKeyField = value;
                this.RaisePropertyChanged("NewEmailKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        public Rol[] Roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("Roles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        public UserPreferences[] Preferences {
            get {
                return this.preferencesField;
            }
            set {
                this.preferencesField = value;
                this.RaisePropertyChanged("Preferences");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class Rol : EntidadBase {
        
        private string roleNameField;
        
        private string descriptionField;
        
        private User[] usersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
                this.RaisePropertyChanged("RoleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public User[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
                this.RaisePropertyChanged("Users");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Country))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Province))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(City))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Address))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Advertiser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Discount))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DiscountCategory))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreferences))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rol))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public abstract partial class EntidadBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class DiscountDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productNameField;
        
        private string descriptionField;
        
        private System.Nullable<decimal> priceField;
        
        private System.Nullable<double> discountPercentField;
        
        private System.Nullable<int> stockQuantityField;
        
        private System.Nullable<int> stockWarningLevelField;
        
        private System.Nullable<System.DateTime> fromDateField;
        
        private System.Nullable<System.DateTime> untilDateField;
        
        private System.Nullable<bool> isPublishedField;
        
        private string commentField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> DiscountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
                this.RaisePropertyChanged("DiscountPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> StockQuantity {
            get {
                return this.stockQuantityField;
            }
            set {
                this.stockQuantityField = value;
                this.RaisePropertyChanged("StockQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> StockWarningLevel {
            get {
                return this.stockWarningLevelField;
            }
            set {
                this.stockWarningLevelField = value;
                this.RaisePropertyChanged("StockWarningLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> UntilDate {
            get {
                return this.untilDateField;
            }
            set {
                this.untilDateField = value;
                this.RaisePropertyChanged("UntilDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsPublished {
            get {
                return this.isPublishedField;
            }
            set {
                this.isPublishedField = value;
                this.RaisePropertyChanged("IsPublished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class Country : EntidadBase {
        
        private string nameField;
        
        private Province[] provincesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Province[] Provinces {
            get {
                return this.provincesField;
            }
            set {
                this.provincesField = value;
                this.RaisePropertyChanged("Provinces");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class Province : EntidadBase {
        
        private string nameField;
        
        private Country countryField;
        
        private City[] citiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Country Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public City[] Cities {
            get {
                return this.citiesField;
            }
            set {
                this.citiesField = value;
                this.RaisePropertyChanged("Cities");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class City : EntidadBase {
        
        private string nameField;
        
        private Province provinceField;
        
        private Address[] addressesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Province Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Address[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
                this.RaisePropertyChanged("Addresses");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class Address : EntidadBase {
        
        private string streetField;
        
        private string postalCodeField;
        
        private User userField;
        
        private City cityField;
        
        private Advertiser[] advertisersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public User User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public City City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public Advertiser[] Advertisers {
            get {
                return this.advertisersField;
            }
            set {
                this.advertisersField = value;
                this.RaisePropertyChanged("Advertisers");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class Advertiser : EntidadBase {
        
        private string nameField;
        
        private string surnameField;
        
        private string userNameField;
        
        private string companyNameField;
        
        private string websiteField;
        
        private string descriptionField;
        
        private string cifField;
        
        private string primaryPhoneField;
        
        private string primaryFaxField;
        
        private string emailField;
        
        private string commentField;
        
        private string passwordField;
        
        private string passwordSaltField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private System.DateTime createDateField;
        
        private System.DateTime lastModifiedDateField;
        
        private System.DateTime lastLoginDateField;
        
        private string lastLoginIpField;
        
        private bool isActivatedField;
        
        private bool isLockedOutField;
        
        private System.Nullable<System.DateTime> lastLockedOutDateField;
        
        private string newPasswordKeyField;
        
        private System.Nullable<System.DateTime> newPasswordRequestedDateField;
        
        private string newEmailKeyField;
        
        private Address addressField;
        
        private Discount[] discountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("Surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Cif {
            get {
                return this.cifField;
            }
            set {
                this.cifField = value;
                this.RaisePropertyChanged("Cif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PrimaryPhone {
            get {
                return this.primaryPhoneField;
            }
            set {
                this.primaryPhoneField = value;
                this.RaisePropertyChanged("PrimaryPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PrimaryFax {
            get {
                return this.primaryFaxField;
            }
            set {
                this.primaryFaxField = value;
                this.RaisePropertyChanged("PrimaryFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PasswordSalt {
            get {
                return this.passwordSaltField;
            }
            set {
                this.passwordSaltField = value;
                this.RaisePropertyChanged("PasswordSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime LastModifiedDate {
            get {
                return this.lastModifiedDateField;
            }
            set {
                this.lastModifiedDateField = value;
                this.RaisePropertyChanged("LastModifiedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime LastLoginDate {
            get {
                return this.lastLoginDateField;
            }
            set {
                this.lastLoginDateField = value;
                this.RaisePropertyChanged("LastLoginDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LastLoginIp {
            get {
                return this.lastLoginIpField;
            }
            set {
                this.lastLoginIpField = value;
                this.RaisePropertyChanged("LastLoginIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
                this.RaisePropertyChanged("IsActivated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool IsLockedOut {
            get {
                return this.isLockedOutField;
            }
            set {
                this.isLockedOutField = value;
                this.RaisePropertyChanged("IsLockedOut");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<System.DateTime> LastLockedOutDate {
            get {
                return this.lastLockedOutDateField;
            }
            set {
                this.lastLockedOutDateField = value;
                this.RaisePropertyChanged("LastLockedOutDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string NewPasswordKey {
            get {
                return this.newPasswordKeyField;
            }
            set {
                this.newPasswordKeyField = value;
                this.RaisePropertyChanged("NewPasswordKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<System.DateTime> NewPasswordRequestedDate {
            get {
                return this.newPasswordRequestedDateField;
            }
            set {
                this.newPasswordRequestedDateField = value;
                this.RaisePropertyChanged("NewPasswordRequestedDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string NewEmailKey {
            get {
                return this.newEmailKeyField;
            }
            set {
                this.newEmailKeyField = value;
                this.RaisePropertyChanged("NewEmailKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public Address Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=26)]
        public Discount[] Discounts {
            get {
                return this.discountsField;
            }
            set {
                this.discountsField = value;
                this.RaisePropertyChanged("Discounts");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class Discount : EntidadBase {
        
        private string productNameField;
        
        private string descriptionField;
        
        private System.Nullable<decimal> priceField;
        
        private System.Nullable<double> discountPercentField;
        
        private System.Nullable<int> stockQuantityField;
        
        private System.Nullable<int> stockWarningLevelField;
        
        private System.Nullable<System.DateTime> fromDateField;
        
        private System.Nullable<System.DateTime> untilDateField;
        
        private System.Nullable<bool> isPublishedField;
        
        private string commentField;
        
        private DiscountCategory discountCategoryField;
        
        private Advertiser advertiserField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("ProductName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<double> DiscountPercent {
            get {
                return this.discountPercentField;
            }
            set {
                this.discountPercentField = value;
                this.RaisePropertyChanged("DiscountPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> StockQuantity {
            get {
                return this.stockQuantityField;
            }
            set {
                this.stockQuantityField = value;
                this.RaisePropertyChanged("StockQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> StockWarningLevel {
            get {
                return this.stockWarningLevelField;
            }
            set {
                this.stockWarningLevelField = value;
                this.RaisePropertyChanged("StockWarningLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
                this.RaisePropertyChanged("FromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> UntilDate {
            get {
                return this.untilDateField;
            }
            set {
                this.untilDateField = value;
                this.RaisePropertyChanged("UntilDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> IsPublished {
            get {
                return this.isPublishedField;
            }
            set {
                this.isPublishedField = value;
                this.RaisePropertyChanged("IsPublished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public DiscountCategory DiscountCategory {
            get {
                return this.discountCategoryField;
            }
            set {
                this.discountCategoryField = value;
                this.RaisePropertyChanged("DiscountCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public Advertiser Advertiser {
            get {
                return this.advertiserField;
            }
            set {
                this.advertiserField = value;
                this.RaisePropertyChanged("Advertiser");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class DiscountCategory : EntidadBase {
        
        private string nameField;
        
        private string descriptionField;
        
        private Discount[] discountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Discount[] Discounts {
            get {
                return this.discountsField;
            }
            set {
                this.discountsField = value;
                this.RaisePropertyChanged("Discounts");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17379")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.iberasoft.com/webservices")]
    public partial class UserPreferences : EntidadBase {
        
        private User userField;
        
        private DiscountCategory discountCategoryPreferredField;
        
        private Advertiser advertiserPreferredField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public User User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DiscountCategory DiscountCategoryPreferred {
            get {
                return this.discountCategoryPreferredField;
            }
            set {
                this.discountCategoryPreferredField = value;
                this.RaisePropertyChanged("DiscountCategoryPreferred");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Advertiser AdvertiserPreferred {
            get {
                return this.advertiserPreferredField;
            }
            set {
                this.advertiserPreferredField = value;
                this.RaisePropertyChanged("AdvertiserPreferred");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DiscountMeServiceSoapChannel : DiscountMe.DiscountMeService.DiscountMeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DiscountMe.DiscountMeService.User Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DiscountMe.DiscountMeService.User)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListaCategoriasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListaCategoriasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DiscountMe.DiscountMeService.DiscountCategory[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DiscountMe.DiscountMeService.DiscountCategory[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DescuentosCercanosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DescuentosCercanosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public DiscountMe.DiscountMeService.DiscountDTO[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((DiscountMe.DiscountMeService.DiscountDTO[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscountMeServiceSoapClient : System.ServiceModel.ClientBase<DiscountMe.DiscountMeService.DiscountMeServiceSoap>, DiscountMe.DiscountMeService.DiscountMeServiceSoap {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginListaCategoriasDelegate;
        
        private EndOperationDelegate onEndListaCategoriasDelegate;
        
        private System.Threading.SendOrPostCallback onListaCategoriasCompletedDelegate;
        
        private BeginOperationDelegate onBeginDescuentosCercanosDelegate;
        
        private EndOperationDelegate onEndDescuentosCercanosDelegate;
        
        private System.Threading.SendOrPostCallback onDescuentosCercanosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DiscountMeServiceSoapClient() {
        }
        
        public DiscountMeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscountMeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountMeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscountMeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<ListaCategoriasCompletedEventArgs> ListaCategoriasCompleted;
        
        public event System.EventHandler<DescuentosCercanosCompletedEventArgs> DescuentosCercanosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscountMe.DiscountMeService.DiscountMeServiceSoap.BeginLogin(string username, string password, string uniqueId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(username, password, uniqueId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscountMe.DiscountMeService.User DiscountMe.DiscountMeService.DiscountMeServiceSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            string uniqueId = ((string)(inValues[2]));
            return ((DiscountMe.DiscountMeService.DiscountMeServiceSoap)(this)).BeginLogin(username, password, uniqueId, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            DiscountMe.DiscountMeService.User retVal = ((DiscountMe.DiscountMeService.DiscountMeServiceSoap)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string username, string password, string uniqueId) {
            this.LoginAsync(username, password, uniqueId, null);
        }
        
        public void LoginAsync(string username, string password, string uniqueId, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        username,
                        password,
                        uniqueId}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscountMe.DiscountMeService.DiscountMeServiceSoap.BeginListaCategorias(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListaCategorias(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscountMe.DiscountMeService.DiscountCategory[] DiscountMe.DiscountMeService.DiscountMeServiceSoap.EndListaCategorias(System.IAsyncResult result) {
            return base.Channel.EndListaCategorias(result);
        }
        
        private System.IAsyncResult OnBeginListaCategorias(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((DiscountMe.DiscountMeService.DiscountMeServiceSoap)(this)).BeginListaCategorias(callback, asyncState);
        }
        
        private object[] OnEndListaCategorias(System.IAsyncResult result) {
            DiscountMe.DiscountMeService.DiscountCategory[] retVal = ((DiscountMe.DiscountMeService.DiscountMeServiceSoap)(this)).EndListaCategorias(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListaCategoriasCompleted(object state) {
            if ((this.ListaCategoriasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListaCategoriasCompleted(this, new ListaCategoriasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListaCategoriasAsync() {
            this.ListaCategoriasAsync(null);
        }
        
        public void ListaCategoriasAsync(object userState) {
            if ((this.onBeginListaCategoriasDelegate == null)) {
                this.onBeginListaCategoriasDelegate = new BeginOperationDelegate(this.OnBeginListaCategorias);
            }
            if ((this.onEndListaCategoriasDelegate == null)) {
                this.onEndListaCategoriasDelegate = new EndOperationDelegate(this.OnEndListaCategorias);
            }
            if ((this.onListaCategoriasCompletedDelegate == null)) {
                this.onListaCategoriasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListaCategoriasCompleted);
            }
            base.InvokeAsync(this.onBeginListaCategoriasDelegate, null, this.onEndListaCategoriasDelegate, this.onListaCategoriasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult DiscountMe.DiscountMeService.DiscountMeServiceSoap.BeginDescuentosCercanos(double latitud, double longitud, string texto, int rango, DiscountMe.DiscountMeService.DiscountCategory category, string medida, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDescuentosCercanos(latitud, longitud, texto, rango, category, medida, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscountMe.DiscountMeService.DiscountDTO[] DiscountMe.DiscountMeService.DiscountMeServiceSoap.EndDescuentosCercanos(System.IAsyncResult result) {
            return base.Channel.EndDescuentosCercanos(result);
        }
        
        private System.IAsyncResult OnBeginDescuentosCercanos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double latitud = ((double)(inValues[0]));
            double longitud = ((double)(inValues[1]));
            string texto = ((string)(inValues[2]));
            int rango = ((int)(inValues[3]));
            DiscountMe.DiscountMeService.DiscountCategory category = ((DiscountMe.DiscountMeService.DiscountCategory)(inValues[4]));
            string medida = ((string)(inValues[5]));
            return ((DiscountMe.DiscountMeService.DiscountMeServiceSoap)(this)).BeginDescuentosCercanos(latitud, longitud, texto, rango, category, medida, callback, asyncState);
        }
        
        private object[] OnEndDescuentosCercanos(System.IAsyncResult result) {
            DiscountMe.DiscountMeService.DiscountDTO[] retVal = ((DiscountMe.DiscountMeService.DiscountMeServiceSoap)(this)).EndDescuentosCercanos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDescuentosCercanosCompleted(object state) {
            if ((this.DescuentosCercanosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DescuentosCercanosCompleted(this, new DescuentosCercanosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DescuentosCercanosAsync(double latitud, double longitud, string texto, int rango, DiscountMe.DiscountMeService.DiscountCategory category, string medida) {
            this.DescuentosCercanosAsync(latitud, longitud, texto, rango, category, medida, null);
        }
        
        public void DescuentosCercanosAsync(double latitud, double longitud, string texto, int rango, DiscountMe.DiscountMeService.DiscountCategory category, string medida, object userState) {
            if ((this.onBeginDescuentosCercanosDelegate == null)) {
                this.onBeginDescuentosCercanosDelegate = new BeginOperationDelegate(this.OnBeginDescuentosCercanos);
            }
            if ((this.onEndDescuentosCercanosDelegate == null)) {
                this.onEndDescuentosCercanosDelegate = new EndOperationDelegate(this.OnEndDescuentosCercanos);
            }
            if ((this.onDescuentosCercanosCompletedDelegate == null)) {
                this.onDescuentosCercanosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDescuentosCercanosCompleted);
            }
            base.InvokeAsync(this.onBeginDescuentosCercanosDelegate, new object[] {
                        latitud,
                        longitud,
                        texto,
                        rango,
                        category,
                        medida}, this.onEndDescuentosCercanosDelegate, this.onDescuentosCercanosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override DiscountMe.DiscountMeService.DiscountMeServiceSoap CreateChannel() {
            return new DiscountMeServiceSoapClientChannel(this);
        }
        
        private class DiscountMeServiceSoapClientChannel : ChannelBase<DiscountMe.DiscountMeService.DiscountMeServiceSoap>, DiscountMe.DiscountMeService.DiscountMeServiceSoap {
            
            public DiscountMeServiceSoapClientChannel(System.ServiceModel.ClientBase<DiscountMe.DiscountMeService.DiscountMeServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(string username, string password, string uniqueId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = username;
                _args[1] = password;
                _args[2] = uniqueId;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public DiscountMe.DiscountMeService.User EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                DiscountMe.DiscountMeService.User _result = ((DiscountMe.DiscountMeService.User)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListaCategorias(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ListaCategorias", _args, callback, asyncState);
                return _result;
            }
            
            public DiscountMe.DiscountMeService.DiscountCategory[] EndListaCategorias(System.IAsyncResult result) {
                object[] _args = new object[0];
                DiscountMe.DiscountMeService.DiscountCategory[] _result = ((DiscountMe.DiscountMeService.DiscountCategory[])(base.EndInvoke("ListaCategorias", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDescuentosCercanos(double latitud, double longitud, string texto, int rango, DiscountMe.DiscountMeService.DiscountCategory category, string medida, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = latitud;
                _args[1] = longitud;
                _args[2] = texto;
                _args[3] = rango;
                _args[4] = category;
                _args[5] = medida;
                System.IAsyncResult _result = base.BeginInvoke("DescuentosCercanos", _args, callback, asyncState);
                return _result;
            }
            
            public DiscountMe.DiscountMeService.DiscountDTO[] EndDescuentosCercanos(System.IAsyncResult result) {
                object[] _args = new object[0];
                DiscountMe.DiscountMeService.DiscountDTO[] _result = ((DiscountMe.DiscountMeService.DiscountDTO[])(base.EndInvoke("DescuentosCercanos", _args, result)));
                return _result;
            }
        }
    }
}
