//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscountMe.Languages.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscountMe.Languages.Idiomas.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountMe.
        /// </summary>
        public static string NombreAplicacion {
            get {
                return ResourceManager.GetString("NombreAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acerca de.
        /// </summary>
        public static string TextoAcercaDe {
            get {
                return ResourceManager.GetString("TextoAcercaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actualizar.
        /// </summary>
        public static string TextoActualizar {
            get {
                return ResourceManager.GetString("TextoActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ajustes.
        /// </summary>
        public static string TextoAjustes {
            get {
                return ResourceManager.GetString("TextoAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atención.
        /// </summary>
        public static string TextoAtencion {
            get {
                return ResourceManager.GetString("TextoAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autores:.
        /// </summary>
        public static string TextoAutores {
            get {
                return ResourceManager.GetString("TextoAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido..
        /// </summary>
        public static string TextoBienvenida {
            get {
                return ResourceManager.GetString("TextoBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string TextoBotonBuscar {
            get {
                return ResourceManager.GetString("TextoBotonBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cerrar sesión.
        /// </summary>
        public static string TextoBotonCerrarSession {
            get {
                return ResourceManager.GetString("TextoBotonCerrarSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        public static string TextoBotonGuardarAjustes {
            get {
                return ResourceManager.GetString("TextoBotonGuardarAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TextoBotonLogin {
            get {
                return ResourceManager.GetString("TextoBotonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buscar.
        /// </summary>
        public static string TextoBuscar {
            get {
                return ResourceManager.GetString("TextoBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajustes.
        /// </summary>
        public static string TextoCategoriaAjustes {
            get {
                return ResourceManager.GetString("TextoCategoriaAjustes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría de búsqueda:.
        /// </summary>
        public static string TextoCategoriaBusqueda {
            get {
                return ResourceManager.GetString("TextoCategoriaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categorías.
        /// </summary>
        public static string TextoCategorias {
            get {
                return ResourceManager.GetString("TextoCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto:.
        /// </summary>
        public static string TextoContacto {
            get {
                return ResourceManager.GetString("TextoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IberaSoft.
        /// </summary>
        public static string TextoContenidoAutores {
            get {
                return ResourceManager.GetString("TextoContenidoAutores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto.
        /// </summary>
        public static string TextoCorrecto {
            get {
                return ResourceManager.GetString("TextoCorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact@iberasoft.com.
        /// </summary>
        public static string TextoDireccionContacto {
            get {
                return ResourceManager.GetString("TextoDireccionContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TextoError {
            get {
                return ResourceManager.GetString("TextoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El GPS está desacitado. Active la recepción GPS en la configuración del teléfono móvil..
        /// </summary>
        public static string TextoGPSDesactivado {
            get {
                return ResourceManager.GetString("TextoGPSDesactivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetros de búsqueda:.
        /// </summary>
        public static string TextoLabelBuscar {
            get {
                return ResourceManager.GetString("TextoLabelBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string TextoLabelEmailUsuario {
            get {
                return ResourceManager.GetString("TextoLabelEmailUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de medida:.
        /// </summary>
        public static string TextoLabelMedidaDeBusqueda {
            get {
                return ResourceManager.GetString("TextoLabelMedidaDeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre:.
        /// </summary>
        public static string TextoLabelNombreUsuario {
            get {
                return ResourceManager.GetString("TextoLabelNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rango de búsqueda:.
        /// </summary>
        public static string TextoLabelRangoDeBusqueda {
            get {
                return ResourceManager.GetString("TextoLabelRangoDeBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mapa de descuentos.
        /// </summary>
        public static string TextoMapaDescuentos {
            get {
                return ResourceManager.GetString("TextoMapaDescuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.
        /// </summary>
        public static string TextoNumeroVersion {
            get {
                return ResourceManager.GetString("TextoNumeroVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña:.
        /// </summary>
        public static string TextoPassword {
            get {
                return ResourceManager.GetString("TextoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to perfil.
        /// </summary>
        public static string TextoPerfil {
            get {
                return ResourceManager.GetString("TextoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordarme:.
        /// </summary>
        public static string TextoRecordarme {
            get {
                return ResourceManager.GetString("TextoRecordarme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del usuario:.
        /// </summary>
        public static string TextoUsuario {
            get {
                return ResourceManager.GetString("TextoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los datos correspondientes al usuario no son correctos..
        /// </summary>
        public static string TextoUsuarioIncorrecto {
            get {
                return ResourceManager.GetString("TextoUsuarioIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versión:.
        /// </summary>
        public static string TextoVersion {
            get {
                return ResourceManager.GetString("TextoVersion", resourceCulture);
            }
        }
    }
}
